[package]
name = "relayvault"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.10.1" }
starknet = "2.3.0"
# starknet = "2.4.2"

[[target.starknet-contract]]
casm = true
sierra = true
# foo = { path = "vendor/foo" }

[tool.snforge]
# exit_first = true


[tool.sncast.emperor] 
account = "emperor"
accounts-file = "/home/hunter/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/c65cc93b1f304e47ae33bf9b050079aa"
# url = "https://starknet-goerli.g.alchemy.com/v2/NaY_MaHTX1z6O-kLCyCK_PQp2rR363DN"
[tool.sncast]
account = "argent_account"
accounts-file = "/home/hunter/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/c65cc93b1f304e47ae33bf9b050079aa"
